name: Check Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check which secrets are available
        run: |
          echo "Checking required secrets..."
          
          echo "CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN != '' && 'SET' || 'MISSING' }}"
          echo "CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID != '' && 'SET' || 'MISSING' }}"
          echo "AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET != '' && 'SET' || 'MISSING' }}"
          echo "MEILI_MASTER_KEY: ${{ secrets.MEILI_MASTER_KEY != '' && 'SET' || 'MISSING' }}"
          echo "MEILI_SEARCH_KEY: ${{ secrets.MEILI_SEARCH_KEY != '' && 'SET' || 'MISSING' }}"
          
          echo ""
          echo "Secret lengths (for verification):"
          echo "AUTH_JWT_SECRET length: ${{ length(secrets.AUTH_JWT_SECRET) }}"
          echo "MEILI_MASTER_KEY length: ${{ length(secrets.MEILI_MASTER_KEY) }}"
          echo "MEILI_SEARCH_KEY length: ${{ length(secrets.MEILI_SEARCH_KEY) }}"
